import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App with Material UI</title>
        <meta
          name="description"
          content="Generated by create next app with next-with-material-ui template"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello, world!</h1>
      </main>
    </>
  );
}
